# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{synaptic4r}
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["troystribling-att"]
  s.date = %q{2009-12-02}
  s.default_executable = %q{synrest}
  s.email = %q{troy.stribling@usi.com}
  s.executables = ["synrest"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/synrest",
     "lib/synaptic4r.rb",
     "lib/synaptic4r/client.rb",
     "lib/synaptic4r/help.rb",
     "lib/synaptic4r/request.rb",
     "lib/synaptic4r/rest.rb",
     "lib/synaptic4r/result.rb",
     "synaptic4r.gemspec",
     "test/create_dir_messages.rb",
     "test/create_dir_test.rb",
     "test/create_file_messages.rb",
     "test/create_file_test.rb",
     "test/get_messages.rb",
     "test/get_test.rb",
     "test/helper.rb",
     "test/matchers.rb",
     "test/mock.rb",
     "test/test.txt"
  ]
  s.homepage = %q{http://github.com/attsynaptic/synaptic4r}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{CLI and Ruby REST Client for ATT Synaptic Storage}
  s.test_files = [
    "test/get_messages.rb",
     "test/create_file_messages.rb",
     "test/get_test.rb",
     "test/create_dir_messages.rb",
     "test/helper.rb",
     "test/create_dir_test.rb",
     "test/create_file_test.rb",
     "test/mock.rb",
     "test/matchers.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, [">= 1.0.2"])
    else
      s.add_dependency(%q<rest-client>, [">= 1.0.2"])
    end
  else
    s.add_dependency(%q<rest-client>, [">= 1.0.2"])
  end
end

